# Generated by Django 4.0.3 on 2022-03-26 21:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Headphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tag', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image_url', models.URLField()),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headphones', to='products.category')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('isbn', models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)])),
                ('pages', models.IntegerField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('status', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='products.category')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
