# Generated by Django 4.0.3 on 2022-03-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='headphones',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Headphones'},
        ),
    ]
