# Generated by Django 4.0.3 on 2022-03-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_books_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
